export struct PackageItem {
    id: string,
    name: string,
    version: string,
    description: string,
    installed: bool,
    icon: image,
    busy: bool,
    progress: float,
    transaction-id: string,
}

export struct DescriptionBlock {
    text: string,
    is-list-item: bool,
    is-heading: bool,
    is-bold: bool,
}

export struct AppDetailData {
    id: string,
    name: string,
    developer: string,
    summary: string,
    version: string,
    icon: image,
    installed: bool,
    flatpak-id: string,
    native-id: string,
    lutris-id: string,
    appimage-id: string,
    flatpak-installed: bool,
    native-installed: bool,
    lutris-installed: bool,
    appimage-installed: bool,
    verified: bool,
    license: string,
    eula-url: string,
    homepage-url: string,
    content-rating: string,
}

export struct AppCardData {
    id: string,
    name: string,
    summary: string,
    icon: image,
    installed: bool,
}

export struct CategoryItem {
    id: string,
    label: string,
    icon: image,
    bg-color: color,
}

export struct ExtensionItem {
    id: string,
    name: string,
    installed: bool,
}

export struct RemoteItem {
    name: string,
    url: string,
    protected: bool,
}

export struct TransactionItem {
    id: string,
    pkg-id: string,
    parent-id: string,
    name: string,
    icon: image,
    progress: float,
    status: string,   // "pending" | "running" | "completed" | "failed"
    tx-type: string,  // "install" | "remove" | "update" | "flatpakref"
    error: string,
}
