services:
  arc-api:
    image: registry.blossomos.org/blossom/arc-store/arc/main:latest
    ports:
      - "1312:1312"
    environment:
      ARC_HTTP_HOST: "0.0.0.0"
      ARC_HTTP_ONLY: "1"
    restart: unless-stopped
