[package]
name = "arc-daemon"
version = "0.1.0"
edition = "2021"

[dependencies.rusqlite]
version = "0.31"
features = ["bundled"]

[[bin]]
name = "arc-daemon"
path = "src/main.rs"

[dependencies]
libarc = { path = "../libarc" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
zbus = { version = "5", features = ["tokio"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
async-trait = "0.1"
futures-util = "0.3"
libflatpak = "0.7"
appstream = { version = "0.2", features = ["gzip"] }
xmltree = "0.10"
reqwest = { version = "0.12", features = ["rustls-tls", "stream", "json"] }
axum = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
serde_yaml = "0.9"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
resvg = "0.44"
flate2 = "1"
scraper = "0.22"
notify = "6"
libc = "0.2"
anvil-appimage = "1.0.1"
krateio = { git = "https://dev.blossomos.org/blossom/krateio.git", tag = "v1.0.0", version = "1.0.0" }
tr = { version = "0.1", default-features = false }
sys-locale = "0.3"

[build-dependencies]
include-po = "0.2"
