import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { AppCardData } from "../types.slint";
import { Badge } from "badge.slint";

export component AppCard inherits Rectangle {
    in property <AppCardData> card;
    in property <bool> is-small: false;
    callback clicked(string);

    border-radius: 10px;
    background: #00000033;
    border-width: 1px;
    border-color: #00000022;

    TouchArea {
        clicked => {
            root.clicked(root.card.id);
        }
    }

    VerticalBox {
        alignment: center;
        padding: root.is-small ? 12px : 16px;
        spacing: root.is-small ? 8px : 10px;

        HorizontalBox {
            alignment: center;
            Rectangle {
                width: root.is-small ? 42px : 76px;
                height: root.is-small ? 42px : 76px;
                border-radius: root.is-small ? 10px : 16px;
                background: #80808012;
                border-width: 1px;
                border-color: #80808025;

                Image {
                    source: root.card.icon;
                    width: root.is-small ? 30px : 60px;
                    height: root.is-small ? 30px : 60px;
                    x: (parent.width - self.width) / 2;
                    y: (parent.height - self.height) / 2;
                    image-fit: contain;
                }
            }
        }

        Text {
            text: root.card.name;
            font-weight: 600;
            font-size: 12px;
            overflow: elide;
            horizontal-alignment: center;
        }

        Text {
            text: root.card.summary;
            font-size: 10px;
            overflow: elide;
            wrap: word-wrap;
            horizontal-alignment: center;
            preferred-height: 24px;
        }

        if root.card.installed: HorizontalLayout {
            alignment: center;
            padding-top: 4px;
            padding-bottom: 4px;
            Badge {
                has-icon: true;
                icon: @image-url("../../assets/check.svg");
                label: "Installed";
            }
        }
    }
}
