export component Badge inherits Rectangle {
    in property <image> icon;
    in property <bool> has-icon: false;
    in property <string> label;
    in property <color> accent: #22c55e;

    height: 18px;
    border-radius: self.height / 2;
    background: root.accent.transparentize(0.82);
    border-width: 1px;
    border-color: root.accent.transparentize(0.55);

    HorizontalLayout {
        padding-left: 6px;
        padding-right: 7px;
        padding-top: 3px;
        padding-bottom: 3px;
        spacing: 4px;
        alignment: center;

        if root.has-icon:
        HorizontalLayout {
            padding-top: 1px;
            Image {
                source: root.icon;
                width: 9px;
                height: 9px;
                vertical-alignment: center;
                colorize: root.accent;
            }
        }

        Text {
            text: root.label;
            font-size: 9px;
            font-weight: 700;
            color: root.accent;
            vertical-alignment: center;
        }
    }
}
