import { Theme } from "../theme.slint";
import { AppCard } from "app-card.slint";
import { AppCardData } from "../types.slint";
import { HScroller } from "h-scroller.slint";

export component Carousel inherits Rectangle {
    in property <[AppCardData]> items;
    in property <string> tr-installed: "Installed";
    callback item-clicked(string);

    property <length> card-w: 196px;
    property <length> card-gap: 12px;

    height: 206px;
    preferred-width: 0px;

    HScroller {
        width: parent.width;
        height: parent.height;
        content-width: root.items.length * (root.card-w + root.card-gap);
        step: 3 * (root.card-w + root.card-gap);
        arrow-bg: Theme.alternate-bg;
        arrow-icon-color: Theme.fg;
        arrow-shadow: true;

        for app[i] in root.items: AppCard {
            x: i * (root.card-w + root.card-gap);
            y: 0px;
            width: root.card-w;
            height: root.height;
            card: app;
            tr-installed: root.tr-installed;
            clicked(id) => {
                root.item-clicked(id);
            }
        }
    }
}
