import { Palette } from "std-widgets.slint";
import { CategoryItem } from "../types.slint";

export component CategoryCard inherits Rectangle {
    in property <CategoryItem> category;
    callback clicked(string);

    border-radius: 12px;
    background: root.category.bg-color;

    ta := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            root.clicked(root.category.id);
        }
    }

    if ta.has-hover: Rectangle {
        width: parent.width;
        height: parent.height;
        border-radius: parent.border-radius;
        background: #ffffff12;
    }

    HorizontalLayout {
        padding: 16px;
        spacing: 14px;

        // Icon
        VerticalLayout {
            alignment: center;
            width: 36px;
            Image {
                source: root.category.icon;
                width: 36px;
                height: 36px;
                image-fit: contain;
            }
        }

        // Label
        VerticalLayout {
            alignment: center;
            Text {
                text: root.category.label;
                font-weight: 700;
                font-size: 14px;
                color: white;
            }
        }
    }
}
