import { Theme } from "../theme.slint";

export component AppProgressBar inherits Rectangle {
    in property <float> progress;

    height: 4px;
    border-radius: self.height / 2;
    background: Theme.track;

    Rectangle {
        x: 0;
        y: 0;
        width: parent.width * root.progress;
        height: parent.height;
        border-radius: parent.border-radius;
        background: Theme.accent;
        animate width {
            duration: 600ms;
            easing: ease-in-out;
        }
    }
}
