import { Palette } from "std-widgets.slint";

export component StatusBar inherits Rectangle {
    in property <string> status-text;

    height: 28px;

    VerticalLayout {
        padding: 0px;
        spacing: 0px;

        Rectangle {
            height: 1px;
            background: #80808025;
        }

        HorizontalLayout {
            padding-left: 12px;
            padding-right: 12px;
            padding-top: 5px;
            padding-bottom: 5px;

            Text {
                text: root.status-text;
                vertical-alignment: center;
                font-size: 11px;
                color: Palette.foreground.transparentize(0.3);
                overflow: elide;
            }
        }
    }
}
