[package]
name = "arc-frontend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "arc-frontend"
path = "src/main.rs"

[dependencies]
libarc = { path = "../libarc" }
tr = { version = "0.1", default-features = false }
sys-locale = "0.3"
slint = "1"
zbus = { version = "5", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
resvg = "0.44"
flate2 = "1"
appstream = { version = "0.2", features = ["gzip"] }
icon-loader = "0.4"
ashpd = { version = "0.13", default-features = false, features = ["settings", "tokio"] }
rust-ini = "0.21.3"
dirs = "6.0.0"

[build-dependencies]
slint-build = "1"
include-po = "0.2"
